name: SYNC
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
env:
  # Username/email used to commit to Cloud Manager's Git repository
  USER_NAME: abhinav.aggarwal@anetcorp.com
  USER_EMAIL: abhinav.aggarwal@anetcorp.com
  # Directory within the Cloud Manager Git repository
  PROJECT_DIR: Practice
  # Cloud Manager's Git repository
  MAIN_REPOSITORY: https://${{secrets.BITBUCKET_USER}}:${{secrets.BITBUCKET_PASSWORD}}@bitbucket.org/aurx-aem/aem-genentech-cm-core.git
  # The branch in Cloud Manager's Git repository to push to
  MAIN_BRANCH : master
on: 
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          path: Practice
      - name: Clean project
        run: |
          git -C Practice log --format="%an : %s" -n 1 > commit.txt
          rm -rf Practice/.git
          rm -rf Practice/.github
      - name: Set git config
        run: |
          git config --global credential.helper cache
          git config --global user.email ${USER_EMAIL}
          git config --global user.name ${USER_NAME}
      - name: Checkout main project
        run:
          git clone -b ${MAIN_BRANCH} ${MAIN_REPOSITORY} ${MAIN_BRANCH}
      - name: Move project to main project
        run: |
          rm -rf ${MAIN_BRANCH}/${PROJECT_DIR}
          mv Practice ${MAIN_BRANCH}/${PROJECT_DIR}
      - name: Commit Changes
        run: |
          git -C ${MAIN_BRANCH} add -f ${PROJECT_DIR}
          git -C ${MAIN_BRANCH} commit -F ../commit.txt
          git -C ${MAIN_BRANCH} push
